

config.football.game_result_topic=game-result-events
config.football.seasons_table=seasons-store
config.football.team_results=team-statistics
config.football.seasons_results=seasons-results

### Kafka Streams Configuration

kafka.bootstrap.servers=localhost:9092
kafka.processing.guarantee=exactly_once_v2
kafka.state.dir=/tmp/teste
quarkus.kafka-streams.bootstrap-servers=${kafka.bootstrap.servers}
quarkus.kafka-streams.application-id=${quarkus.application.name}

quarkus.kafka-streams.application-server=${hostname}:80802
#quarkus.kafka-streams.topics=${config.football.game_result_topic},${config.foolball.team_results},${config.football.seasons_results}

# pass-through options
kafka-streams.cache.max.bytes.buffering=10240
kafka-streams.commit.interval.ms=1000
kafka-streams.metadata.max.age.ms=500
kafka-streams.auto.offset.reset=earliest
kafka-streams.metrics.recording.level=DEBUG

kafka-streams.consumer.session.timeout.ms=250
kafka-streams.consumer.heartbeat.interval.ms=200